### ISSUE TITLE
java.lang.IllegalArgumentException: Quantity (4) exceeded the maximum stack size (1)

### ISSUE THREAD

**Issue by clienthax** [Time6628/Market#12]
Ive been told this happened after someone put a loot bag onto the market (from skyfactory 3)
Appears when attempting to load the market listings

```
java.lang.IllegalArgumentException: Quantity (4) exceeded the maximum stack size (1)
        at net.minecraft.item.ItemStack.setQuantity(ItemStack.java:2292) ~[adz.class:?]
        at com.kookykraftmc.market.datastores.ListingUI.getActionableElement(ListingUI.java:26) ~[ListingUI.class:?]
        at com.kookykraftmc.market.datastores.UIManager.lambda$getStateContainer$2(UIManager.java:38) ~[UIManager.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1255) ~[?:1.8.0_151]
        at com.kookykraftmc.market.datastores.UIManager.getStateContainer(UIManager.java:38) ~[UIManager.class:?]
        at com.kookykraftmc.market.commands.subcommands.ListingsCommand.execute(ListingsCommand.java:22) ~[ListingsCommand.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.10.2-2477-5.2.0-BETA-2788]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2477-5.2.0-BETA-2788]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2477-5.2.0-BETA-2788]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2477-5.2.0-BETA-2788]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2477-5.2.0-BETA-2788]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) [CauseTracker.class:1.10.2-2477-5.2.0-BETA-2788]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2477-5.2.0-BETA-2788]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-2477-5.2.0-BETA-2788]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3948) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
>
```

**Comment by clienthax** [comment]
Seems that changing that line to
```
i.setQuantity(Math.min(listing.getQuantity(), i.getMaxStackQuantity()));
```
 Makes it all happy, not sure if thats the correct way however

**Comment by ryantheleach** [comment]
That's not a fix. (I suspect there is already) but there needs to be a natural way to exceed the maximum natural stack size if mods + other things support it.

**Comment by Time6628** [comment]
This line is just supposed to be so players can see how many of an item they're buying without putting too much text in the lore of the item. You can't set the ItemStack to a greater quantity in API5, but you can in the later api versions of Sponge. Not sure if this is a limitation of Sponge or Minecraft itself, but I'll have a fix for this later today.

**Comment by clienthax** [comment]
@Time6628 Thanks!
This is on the dbsandinv branch with it set for api 5 :)
I did also hit an issue when it attempted to run the buy command as it has the same code for making the itemstack, wonder if its possible to just recreate it from the snapshot / store that in redis instead?
